//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FinReport", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FinReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        private int ReportIDField;
        
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ReportID {
            get {
                return this.ReportIDField;
            }
            set {
                if ((this.ReportIDField.Equals(value) != true)) {
                    this.ReportIDField = value;
                    this.RaisePropertyChanged("ReportID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Info {
            get {
                return this.InfoField;
            }
            set {
                if ((object.ReferenceEquals(this.InfoField, value) != true)) {
                    this.InfoField = value;
                    this.RaisePropertyChanged("Info");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.FinReportServiceSoap")]
    public interface FinReportServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем GetReportIdArrayResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportIdArray", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.GetReportIdArrayResponse GetReportIdArray(WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReportIdArray", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.GetReportIdArrayResponse> GetReportIdArrayAsync(WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем My_timeZoneResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/My_timeZone", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.My_timeZoneResponse My_timeZone(WindowsFormsApplication1.ServiceReference1.My_timeZoneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/My_timeZone", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.My_timeZoneResponse> My_timeZoneAsync(WindowsFormsApplication1.ServiceReference1.My_timeZoneRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetReportResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.GetReportResponse GetReport(WindowsFormsApplication1.ServiceReference1.GetReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReport", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.GetReportResponse> GetReportAsync(WindowsFormsApplication1.ServiceReference1.GetReportRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем Time из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimeZones", ReplyAction="*")]
        WindowsFormsApplication1.ServiceReference1.TimeZonesResponse TimeZones(WindowsFormsApplication1.ServiceReference1.TimeZonesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TimeZones", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.TimeZonesResponse> TimeZonesAsync(WindowsFormsApplication1.ServiceReference1.TimeZonesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportIdArrayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportIdArray", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequestBody Body;
        
        public GetReportIdArrayRequest() {
        }
        
        public GetReportIdArrayRequest(WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportIdArrayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime dateBegin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime dateEnd;
        
        public GetReportIdArrayRequestBody() {
        }
        
        public GetReportIdArrayRequestBody(System.DateTime dateBegin, System.DateTime dateEnd) {
            this.dateBegin = dateBegin;
            this.dateEnd = dateEnd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportIdArrayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportIdArrayResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.GetReportIdArrayResponseBody Body;
        
        public GetReportIdArrayResponse() {
        }
        
        public GetReportIdArrayResponse(WindowsFormsApplication1.ServiceReference1.GetReportIdArrayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportIdArrayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ServiceReference1.ArrayOfInt GetReportIdArrayResult;
        
        public GetReportIdArrayResponseBody() {
        }
        
        public GetReportIdArrayResponseBody(WindowsFormsApplication1.ServiceReference1.ArrayOfInt GetReportIdArrayResult) {
            this.GetReportIdArrayResult = GetReportIdArrayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class My_timeZoneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="My_timeZone", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.My_timeZoneRequestBody Body;
        
        public My_timeZoneRequest() {
        }
        
        public My_timeZoneRequest(WindowsFormsApplication1.ServiceReference1.My_timeZoneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class My_timeZoneRequestBody {
        
        public My_timeZoneRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class My_timeZoneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="My_timeZoneResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.My_timeZoneResponseBody Body;
        
        public My_timeZoneResponse() {
        }
        
        public My_timeZoneResponse(WindowsFormsApplication1.ServiceReference1.My_timeZoneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class My_timeZoneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string My_timeZoneResult;
        
        public My_timeZoneResponseBody() {
        }
        
        public My_timeZoneResponseBody(string My_timeZoneResult) {
            this.My_timeZoneResult = My_timeZoneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReport", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.GetReportRequestBody Body;
        
        public GetReportRequest() {
        }
        
        public GetReportRequest(WindowsFormsApplication1.ServiceReference1.GetReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int reportID;
        
        public GetReportRequestBody() {
        }
        
        public GetReportRequestBody(int reportID) {
            this.reportID = reportID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.GetReportResponseBody Body;
        
        public GetReportResponse() {
        }
        
        public GetReportResponse(WindowsFormsApplication1.ServiceReference1.GetReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WindowsFormsApplication1.ServiceReference1.FinReport GetReportResult;
        
        public GetReportResponseBody() {
        }
        
        public GetReportResponseBody(WindowsFormsApplication1.ServiceReference1.FinReport GetReportResult) {
            this.GetReportResult = GetReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimeZonesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimeZones", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.TimeZonesRequestBody Body;
        
        public TimeZonesRequest() {
        }
        
        public TimeZonesRequest(WindowsFormsApplication1.ServiceReference1.TimeZonesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TimeZonesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Time;
        
        public TimeZonesRequestBody() {
        }
        
        public TimeZonesRequestBody(string Time) {
            this.Time = Time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TimeZonesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TimeZonesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.ServiceReference1.TimeZonesResponseBody Body;
        
        public TimeZonesResponse() {
        }
        
        public TimeZonesResponse(WindowsFormsApplication1.ServiceReference1.TimeZonesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TimeZonesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TimeZonesResult;
        
        public TimeZonesResponseBody() {
        }
        
        public TimeZonesResponseBody(string TimeZonesResult) {
            this.TimeZonesResult = TimeZonesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FinReportServiceSoapChannel : WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinReportServiceSoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap>, WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap {
        
        public FinReportServiceSoapClient() {
        }
        
        public FinReportServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinReportServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinReportServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinReportServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.GetReportIdArrayResponse WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap.GetReportIdArray(WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequest request) {
            return base.Channel.GetReportIdArray(request);
        }
        
        public WindowsFormsApplication1.ServiceReference1.ArrayOfInt GetReportIdArray(System.DateTime dateBegin, System.DateTime dateEnd) {
            WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequest inValue = new WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequestBody();
            inValue.Body.dateBegin = dateBegin;
            inValue.Body.dateEnd = dateEnd;
            WindowsFormsApplication1.ServiceReference1.GetReportIdArrayResponse retVal = ((WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap)(this)).GetReportIdArray(inValue);
            return retVal.Body.GetReportIdArrayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.GetReportIdArrayResponse> WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap.GetReportIdArrayAsync(WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequest request) {
            return base.Channel.GetReportIdArrayAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.GetReportIdArrayResponse> GetReportIdArrayAsync(System.DateTime dateBegin, System.DateTime dateEnd) {
            WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequest inValue = new WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.GetReportIdArrayRequestBody();
            inValue.Body.dateBegin = dateBegin;
            inValue.Body.dateEnd = dateEnd;
            return ((WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap)(this)).GetReportIdArrayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.My_timeZoneResponse WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap.My_timeZone(WindowsFormsApplication1.ServiceReference1.My_timeZoneRequest request) {
            return base.Channel.My_timeZone(request);
        }
        
        public string My_timeZone() {
            WindowsFormsApplication1.ServiceReference1.My_timeZoneRequest inValue = new WindowsFormsApplication1.ServiceReference1.My_timeZoneRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.My_timeZoneRequestBody();
            WindowsFormsApplication1.ServiceReference1.My_timeZoneResponse retVal = ((WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap)(this)).My_timeZone(inValue);
            return retVal.Body.My_timeZoneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.My_timeZoneResponse> WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap.My_timeZoneAsync(WindowsFormsApplication1.ServiceReference1.My_timeZoneRequest request) {
            return base.Channel.My_timeZoneAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.My_timeZoneResponse> My_timeZoneAsync() {
            WindowsFormsApplication1.ServiceReference1.My_timeZoneRequest inValue = new WindowsFormsApplication1.ServiceReference1.My_timeZoneRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.My_timeZoneRequestBody();
            return ((WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap)(this)).My_timeZoneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.GetReportResponse WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap.GetReport(WindowsFormsApplication1.ServiceReference1.GetReportRequest request) {
            return base.Channel.GetReport(request);
        }
        
        public WindowsFormsApplication1.ServiceReference1.FinReport GetReport(int reportID) {
            WindowsFormsApplication1.ServiceReference1.GetReportRequest inValue = new WindowsFormsApplication1.ServiceReference1.GetReportRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.GetReportRequestBody();
            inValue.Body.reportID = reportID;
            WindowsFormsApplication1.ServiceReference1.GetReportResponse retVal = ((WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap)(this)).GetReport(inValue);
            return retVal.Body.GetReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.GetReportResponse> WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap.GetReportAsync(WindowsFormsApplication1.ServiceReference1.GetReportRequest request) {
            return base.Channel.GetReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.GetReportResponse> GetReportAsync(int reportID) {
            WindowsFormsApplication1.ServiceReference1.GetReportRequest inValue = new WindowsFormsApplication1.ServiceReference1.GetReportRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.GetReportRequestBody();
            inValue.Body.reportID = reportID;
            return ((WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap)(this)).GetReportAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.ServiceReference1.TimeZonesResponse WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap.TimeZones(WindowsFormsApplication1.ServiceReference1.TimeZonesRequest request) {
            return base.Channel.TimeZones(request);
        }
        
        public string TimeZones(string Time) {
            WindowsFormsApplication1.ServiceReference1.TimeZonesRequest inValue = new WindowsFormsApplication1.ServiceReference1.TimeZonesRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.TimeZonesRequestBody();
            inValue.Body.Time = Time;
            WindowsFormsApplication1.ServiceReference1.TimeZonesResponse retVal = ((WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap)(this)).TimeZones(inValue);
            return retVal.Body.TimeZonesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.TimeZonesResponse> WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap.TimeZonesAsync(WindowsFormsApplication1.ServiceReference1.TimeZonesRequest request) {
            return base.Channel.TimeZonesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApplication1.ServiceReference1.TimeZonesResponse> TimeZonesAsync(string Time) {
            WindowsFormsApplication1.ServiceReference1.TimeZonesRequest inValue = new WindowsFormsApplication1.ServiceReference1.TimeZonesRequest();
            inValue.Body = new WindowsFormsApplication1.ServiceReference1.TimeZonesRequestBody();
            inValue.Body.Time = Time;
            return ((WindowsFormsApplication1.ServiceReference1.FinReportServiceSoap)(this)).TimeZonesAsync(inValue);
        }
    }
}
